# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-23 03:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truck_route', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='truckroute',
            name='date_added',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='truckroute',
            name='route_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='truckroute',
            name='truck_number',
            field=models.IntegerField(),
        ),
        migrations.RemoveField(
            model_name='truckroute',
            name='date_updated',
        ),
        migrations.AlterUniqueTogether(
            name='truckroute',
            unique_together=set([('truck_number', 'route_number', 'date_added')]),
        ),
    ]
