# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-23 04:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('truck_route', '0004_auto_20160423_0454'),
    ]

    operations = [
        migrations.RenameField(
            model_name='truckroute',
            old_name='route',
            new_name='route_number',
        ),
        migrations.RenameField(
            model_name='truckroute',
            old_name='truck',
            new_name='truck_number',
        ),
        migrations.AlterUniqueTogether(
            name='truckroute',
            unique_together=set([('truck_number', 'route_number', 'date_added')]),
        ),
    ]
