# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-25 00:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truck_route', '0005_auto_20160423_0455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='truckroute',
            name='date_added',
            field=models.DateField(),
        ),
    ]
