# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-06 01:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trucks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='truck',
            name='truck_number',
            field=models.IntegerField(),
        ),
    ]
