MAX_CITIES = 10
#Action Boundry
ACTION_S = 0
ACTION_L = 1
ACTION_E = ACTION_S + ACTION_L
#Route Number Boundry
ROUTE_N_S = ACTION_E
ROUTE_N_L = 4
ROUTE_N_E = ROUTE_N_S + ROUTE_N_L
#Cities Boundry
CITIES_S = ROUTE_N_E
CITIES_L = 20
CITIES_E = None
