TR_NUM_S = 3
TR_NUM_L = 4
TR_NUM_E = TR_NUM_S + TR_NUM_L

ITEM_NUM_S = 0
ITEM_NUM_L = 4
ITEM_NUM_E = ITEM_NUM_S + ITEM_NUM_L

FINAL_Q_S = ITEM_NUM_E
FINAL_Q_L = 4
FINAL_Q_E = FINAL_Q_S + FINAL_Q_L

SR_NUM_S = 3
SR_NUM_L = 4
SR_NUM_E = SR_NUM_S + SR_NUM_L
