TR_NUM_S = 3
TR_NUM_L = 4
TR_NUM_E = TR_NUM_S + TR_NUM_L

ITEM_NUM_S = 0
ITEM_NUM_L = 4
ITEM_NUM_E = ITEM_NUM_S + ITEM_NUM_L

ADJUSTMENT_S = ITEM_NUM_E
ADJUSTMENT_L = 4
ADJUSTMENT_E = ADJUSTMENT_S + ADJUSTMENT_L

IR_NUM_S = 3
IR_NUM_L = 4
IR_NUM_E = IR_NUM_S + IR_NUM_L

MAX_ITEMS = 10
