# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-23 03:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0002_auto_20160406_0107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='route_number',
            field=models.IntegerField(unique=True),
        ),
    ]
