# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-23 03:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0002_auto_20160422_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='route',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='routes.Route'),
        ),
    ]
