# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-08 00:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('warehouse_inventory', '0001_initial'),
        ('trucks', '0002_auto_20160406_0147'),
    ]

    operations = [
        migrations.CreateModel(
            name='TruckInventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('quantity', models.IntegerField()),
                ('item_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse_inventory.WarehouseInventory')),
                ('truck_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trucks.Truck')),
            ],
        ),
    ]
