# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-26 07:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truck_inventory', '0003_truckinventory_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='truckinventory',
            name='date_added',
            field=models.DateField(null=True),
        ),
    ]
