# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-24 04:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upload',
            name='date_updated',
        ),
        migrations.AlterField(
            model_name='upload',
            name='date_added',
            field=models.DateField(),
        ),
    ]
