# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-24 05:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0002_auto_20160424_0458'),
    ]

    operations = [
        migrations.RenameField(
            model_name='upload',
            old_name='type_of_file',
            new_name='file_type',
        ),
    ]
