# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-26 01:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('day_status', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daystatus',
            name='login_date',
            field=models.DateField(unique=True),
        ),
    ]
