# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-08 00:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sales', '0001_initial'),
        ('truck_route', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='truck_route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='truck_route.TruckRoute'),
        ),
    ]
