# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-25 00:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_auto_20160424_0607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='date_added',
            field=models.DateField(default=datetime.datetime(2016, 4, 25, 0, 4, 5, 983874, tzinfo=utc)),
        ),
    ]
