# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-25 00:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_auto_20160425_0004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='date_added',
            field=models.DateField(),
        ),
    ]
